# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e55064e7850bca5ea63b448694faa926fbdd1e6d62fae51c35518e87a2172df8c153e3bb8752d87a3c89b24047287d1b969e2ab3a4cee82719ee6b51ac374f19

test:
  secret_key_base: 07d9493b3a56b4f9893376c11c9f71f7b2b8b9f978844ee4efe34a709b39c7c53047915664db62debcd43beae2cb91e4dd05013b58b96a95a166f5d978f57c90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
